import React from 'react'

export const metadata = {
  title: 'Ethics and Use Policy | Roast-O-Matic',
  description: 'Our commitment to responsible AI usage and ethical roasting.',
}

export default function EthicsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 text-center">Ethics and Use Policy for Roast-O-Matic</h1>
      
      <p className="mb-6">Welcome to Roast-O-Matic!</p>

      <p className="mb-6">Roast-O-Matic is designed to bring humor and light-hearted fun to your day. However, with great roasting comes great responsibility. We want to ensure everyone enjoys their experience while understanding the limitations and ethics of using AI-generated content. Please read this policy carefully to understand our stance on responsible use and what to expect.</p>

      <h2 className="text-2xl font-semibold mb-4">1. A Personal Note from the Creator</h2>

      <p className="mb-6">Roast-O-Matic is a labor of love created by a solo developer from India. Actually, I am not a traditional developer—I use AI to build apps. This app was built using AI tools like v0.dev. I humbly request everyone to:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Avoid Spamming:</strong> Please do not spam or abuse the tool and its features.</li>
        <li><strong>Use Responsibly:</strong> Don't exploit the platform in the wrong way. This is an attempt to bring laughter to everyone.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">2. Respectful Usage</h2>

      <p className="mb-6">Roast-O-Matic is intended for fun, playful banter. We ask all users to:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Maintain Light-Heartedness:</strong> Keep the interactions fun and don't take things too seriously. Remember, this is meant to be a humorous tool.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">3. AI Limitations</h2>

      <p className="mb-6">While we strive to ensure Roast-O-Matic provides witty and enjoyable content, it's important to recognize the following:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>AI-Generated Content:</strong> The responses you receive are generated by an AI model. Despite our best efforts to filter and guide the AI, it can sometimes produce content that may be inappropriate, insensitive, or offensive.</li>
        <li><strong>Unintentional Offense:</strong> AI can make mistakes or misunderstand context, leading to replies that could be perceived as offensive. These instances are not reflective of our values or intentions.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">4. Handling Potential Offense</h2>

      <p className="mb-6">If you encounter content that you find offensive or inappropriate:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Don't Take It Personally:</strong> Remember, the responses are generated by AI without personal intent.</li>
        <li><strong>Report the Issue:</strong> Please use our reporting feature to flag inappropriate content so we can review and improve our systems.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">5. Content Sensitivity</h2>

      <p className="mb-6">Roast-O-Matic aims to maintain a balance between humor and sensitivity. However, due to the unpredictable nature of AI, some content might:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Contain Stereotypes:</strong> While we aim to avoid reinforcing stereotypes, the AI may inadvertently use commonly known references.</li>
        <li><strong>Touch on Sensitive Topics:</strong> AI might generate responses that involve sensitive or controversial topics. We do our best to prevent this but ask users to be understanding if it occurs.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">6. User Responsibility</h2>

      <p className="mb-6">By using Roast-O-Matic, you agree to:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Use the Platform Responsibly:</strong> Engage in a way that contributes positively to the experience for yourself and others.</li>
        <li><strong>Avoid Malicious Behavior:</strong> Do not attempt to misuse the platform to generate harmful or offensive content deliberately.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">7. Our Commitment</h2>

      <p className="mb-6">We are committed to:</p>

      <ul className="list-disc pl-6 mb-6">
        <li><strong>Improving AI Accuracy:</strong> Continuously refining our AI to minimize offensive or inappropriate outputs.</li>
        <li><strong>User Feedback:</strong> Actively reviewing user feedback to improve the platform's performance and content quality.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">8. Contact Us</h2>

      <p className="mb-6">If you have any concerns, feedback, or questions about your experience with Roast-O-Matic, please contact at support@roastomatic.com.</p>

      <p className="mb-6">By using Roast-O-Matic, you acknowledge that AI can make mistakes, and you agree to engage with the platform in a fun, respectful, and responsible manner. Let's keep the roasts witty and enjoyable for everyone!</p>
    </div>
  )
}

